Importo las librerías para trabajar ETL y EDA

In [1]:
import pandas as pd
import numpy as np

Ingesta de archivos csv

In [3]:
dfamz = pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/amazon_prime_titles.csv')
dfdis = pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/disney_plus_titles.csv')
dfhul = pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/hulu_titles.csv')
dfnet = pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/netflix_titles.csv')

Arranco el proceso de EDA (Exploraty Data Anaysis)

In [4]:
dfamz.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       9668 non-null   object
 1   type          9668 non-null   object
 2   title         9668 non-null   object
 3   director      7586 non-null   object
 4   cast          8435 non-null   object
 5   country       672 non-null    object
 6   date_added    155 non-null    object
 7   release_year  9668 non-null   int64
 8   rating        9331 non-null   object
 9   duration      9668 non-null   object
 10  listed_in     9668 non-null   object
 11  description   9668 non-null   object
dtypes: int64(1), object(11)
memory usage: 906.5+ KB

In [5]:
dfdis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       1450 non-null   object
 1   type          1450 non-null   object
 2   title         1450 non-null   object
 3   director      977 non-null    object
 4   cast          1260 non-null   object
 5   country       1231 non-null   object
 6   date_added    1447 non-null   object
 7   release_year  1450 non-null   int64
 8   rating        1447 non-null   object
 9   duration      1450 non-null   object
 10  listed_in     1450 non-null   object
 11  description   1450 non-null   object
dtypes: int64(1), object(11)
memory usage: 136.1+ KB

In [6]:
dfhul.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3073 entries, 0 to 3072
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       3073 non-null   object
 1   type          3073 non-null   object
 2   title         3073 non-null   object
 3   director      3 non-null      object
 4   cast          0 non-null      float64
 5   country       1620 non-null   object
 6   date_added    3045 non-null   object
 7   release_year  3073 non-null   int64
 8   rating        2553 non-null   object
 9   duration      2594 non-null   object
 10  listed_in     3073 non-null   object
 11  description   3069 non-null   object
dtypes: float64(1), int64(1), object(10)
memory usage: 288.2+ KB

In [7]:
dfnet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

Observo los datos de cada dataframe

In [8]:
dfamz.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...

In [9]:
dfdis.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...

In [10]:
dfhul.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Ricky Velez: Here's Everything,NaN,NaN,NaN,"October 24, 2021",2021,TV-MA,NaN,"Comedy, Stand Up",​Comedian Ricky Velez bares it all with his ho...
1,s2,Movie,Silent Night,NaN,NaN,NaN,"October 23, 2021",2020,NaN,94 min,"Crime, Drama, Thriller","Mark, a low end South London hitman recently r..."

In [11]:
dfnet.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

Ver la cantidad de filas y columnas

In [12]:
dfamz.shape

(9668, 12)

In [13]:
dfdis.shape

(1450, 12)

In [14]:
dfhul.shape

(3073, 12)

In [15]:
dfnet.shape

(8807, 12)

Busco y sumo valores nulos

In [16]:
dfamz.isna().sum()

show_id            0
type               0
title              0
director        2082
cast            1233
country         8996
date_added      9513
release_year       0
rating           337
duration           0
listed_in          0
description        0
dtype: int64

In [17]:
dfdis.isna().sum()

show_id           0
type              0
title             0
director        473
cast            190
country         219
date_added        3
release_year      0
rating            3
duration          0
listed_in         0
description       0
dtype: int64

In [18]:
dfhul.isna().sum()

show_id            0
type               0
title              0
director        3070
cast            3073
country         1453
date_added        28
release_year       0
rating           520
duration         479
listed_in          0
description        4
dtype: int64

In [19]:
dfnet.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

Agrego columna 'plataforma'

In [20]:
dfamz['plataforma']='amazon'

In [21]:
dfdis['plataforma']='disney'

In [22]:
dfhul['plataforma']='hulu'

In [24]:
dfnet['plataforma']='netflix'

Genero el campo 'id'

In [25]:
dfamz.insert(loc=0, column="id", value="a" + dfamz["show_id"])
dfamz.tail(1)

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,plataforma
9667,as9668,s9668,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",NaN,NaN,2010,R,103 min,"Action, Drama, Suspense","Harry Brown, starring two-time Academy Award w...",amazon

In [26]:
dfdis.insert(loc=0, column="id", value="d" + dfamz["show_id"])
dfdis.tail(1)

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,plataforma
1449,ds1450,s1450,Movie,Captain Sparky vs. The Flying Saucers,Mark Waring,Charlie Tahan,United States,"April 1, 2020",2012,TV-G,2 min,"Action-Adventure, Animals & Nature, Animation",View one of Sparky's favorite home movies.,disney

In [27]:
dfhul.insert(loc=0, column="id", value="h" + dfamz["show_id"])
dfhul.tail(1)

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,plataforma
3072,hs3073,s3073,TV Show,Tokyo Magnitude 8.0,NaN,NaN,Japan,NaN,2009,TV-14,1 Season,"Anime, Drama, International",The devastation is unleashed in the span of se...,hulu

In [28]:
dfnet.insert(loc=0, column="id", value="n" + dfamz["show_id"])
dfnet

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,plataforma
0,ns1,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",netflix
1,ns2,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",netflix
2,ns3,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,netflix
3,ns4,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",netflix
4,ns5,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,netflix
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,ns8803,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",netflix
8803,ns8804,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",netflix
8804,ns8805,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,netflix
8805,ns8806,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",netflix
8806,ns8807,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,netflix

Concateno de los df

In [29]:
plataformas = (pd.concat([dfamz,dfdis,dfhul,dfnet], axis=0))
plataformas.shape

(22998, 14)

Reemplazo en la columna 'Rating' los valores nulos por 'G'

In [30]:
plataformas['rating'] = plataformas['rating'].fillna('G')
plataformas

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,plataforma
0,as1,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,G,113 min,"Comedy, Drama",A small fishing village must procure a local d...,amazon
1,as2,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,amazon
2,as3,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,G,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,amazon
3,as4,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,G,69 min,Documentary,"Pink breaks the mold once again, bringing her ...",amazon
4,as5,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,G,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,amazon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,ns8803,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",netflix
8803,ns8804,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",netflix
8804,ns8805,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,netflix
8805,ns8806,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",netflix
8806,ns8807,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,netflix

Cambio el formato del campo 'data_added'

In [31]:
plataformas['date_added'] = pd.to_datetime(plataformas['date_added'])
plataformas

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,plataforma
0,as1,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,2021-03-30,2014,G,113 min,"Comedy, Drama",A small fishing village must procure a local d...,amazon
1,as2,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,2021-03-30,2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,amazon
2,as3,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,2021-03-30,2017,G,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,amazon
3,as4,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,2021-03-30,2014,G,69 min,Documentary,"Pink breaks the mold once again, bringing her ...",amazon
4,as5,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,2021-03-30,1989,G,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,amazon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,ns8803,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",netflix
8803,ns8804,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,2019-07-01,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",netflix
8804,ns8805,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,netflix
8805,ns8806,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",netflix
8806,ns8807,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,netflix

Reemplazo las letras mayusculas por minusculas

In [32]:
plataformas['title']=plataformas['title'].str.lower()
plataformas['type']=plataformas['type'].str.lower()
plataformas['director']=plataformas['director'].str.lower()
plataformas['cast']=plataformas['cast'].str.lower()
plataformas['country']=plataformas['country'].str.lower()
plataformas['listed_in']=plataformas['listed_in'].str.lower()
plataformas['description']=plataformas['description'].str.lower()
plataformas.tail()

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,plataforma
8802,ns8803,s8803,movie,zodiac,david fincher,"mark ruffalo, jake gyllenhaal, robert downey j...",united states,2019-11-20,2007,R,158 min,"cult movies, dramas, thrillers","a political cartoonist, a crime reporter and a...",netflix
8803,ns8804,s8804,tv show,zombie dumb,NaN,NaN,NaN,2019-07-01,2018,TV-Y7,2 Seasons,"kids' tv, korean tv shows, tv comedies","while living alone in a spooky town, a young g...",netflix
8804,ns8805,s8805,movie,zombieland,ruben fleischer,"jesse eisenberg, woody harrelson, emma stone, ...",united states,2019-11-01,2009,R,88 min,"comedies, horror movies",looking to survive in a world taken over by zo...,netflix
8805,ns8806,s8806,movie,zoom,peter hewitt,"tim allen, courteney cox, chevy chase, kate ma...",united states,2020-01-11,2006,PG,88 min,"children & family movies, comedies","dragged from civilian life, a former superhero...",netflix
8806,ns8807,s8807,movie,zubaan,mozez singh,"vicky kaushal, sarah-jane dias, raaghav chanan...",india,2019-03-02,2015,TV-14,111 min,"dramas, international movies, music & musicals",a scrappy but poor boy worms his way into a ty...,netflix

Divido el campo duracion para poder identificar las peliculas de las series

In [33]:
div = plataformas["duration"].str.split(' ', n=1, expand=True)
plataformas["duration_int"] = div[0]
plataformas["duration_type"] = div[1]
plataformas.head(1)

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,plataforma,duration_int,duration_type
0,as1,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,G,113 min,"comedy, drama",a small fishing village must procure a local d...,amazon,113,min

In [34]:
plataformas["duration_int"] = plataformas["duration_int"].fillna(0)
plataformas['duration_int'] = plataformas['duration_int'].astype('int64')

In [35]:
plataformas = plataformas.fillna('Sin dato')
plataformas.isna().sum()

id               0
show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added       0
release_year     0
rating           0
duration         0
listed_in        0
description      0
plataforma       0
duration_int     0
duration_type    0
dtype: int64

Ahora ingesto los archivos raiting que los necesito para las siguientes etapas

In [37]:
dfr1 = pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/1.csv')
dfr2 = pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/2.csv')
dfr3 = pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/3.csv')
dfr4 = pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/4.csv')
dfr5 = pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/5.csv')
dfr6 = pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/6.csv')
dfr7 = pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/7.csv')
dfr8 = pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/8.csv')

Concateno de los df

In [38]:
ratings = (pd.concat([dfr1,dfr2,dfr3,dfr4,dfr5,dfr6,dfr7,dfr8], axis=0))
ratings

         userId  rating   timestamp movieId
0             1     1.0  1425941529   as680
1             1     4.5  1425942435  ns2186
2             1     5.0  1425941523  hs2381
3             1     5.0  1425941546  ns3663
4             1     5.0  1425941556  as9500
...         ...     ...         ...     ...
1499995  124380     4.5  1196786159  ns5272
1499996  124380     2.5  1196786030  ns5492
1499997  124380     3.5  1196785679   hs305
1499998  124380     4.5  1196787089  ns7881
1499999  124380     1.5  1196785847   as883

[11024289 rows x 4 columns]

Arranco el proceso de EDA (Exploraty Data Anaysis)

In [39]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11024289 entries, 0 to 1499999
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   rating     float64
 2   timestamp  int64
 3   movieId    object
dtypes: float64(1), int64(2), object(1)
memory usage: 420.5+ MB

Ver la cantidad de filas y columnas

In [40]:
ratings.shape

(11024289, 4)

Busco y sumo valores nulos

In [41]:
ratings.isna().sum()

userId       0
rating       0
timestamp    0
movieId      0
dtype: int64

Calculo la media de las valoraciones, agrupando por "movieId"

In [42]:
mean_score= ratings.groupby('movieId')['rating'].mean()

Elimino los duplicados

In [43]:
ratings =ratings.drop_duplicates(subset='movieId')

Agrego la columna 'score' con la valoracion de los usuarios de cada pelicula

In [44]:
plataformas['score'] = ratings.groupby('movieId')['rating'].transform(lambda x: mean_score.loc[x.name])

In [45]:
plataformas.head()

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,plataforma,duration_int,duration_type,score
0,as1,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30 00:00:00,2014,G,113 min,"comedy, drama",a small fishing village must procure a local d...,amazon,113,min,3.549127
1,as2,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30 00:00:00,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,amazon,110,min,3.556886
2,as3,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30 00:00:00,2017,G,74 min,"action, drama, suspense",after a man discovers his wife is cheating on ...,amazon,74,min,3.604124
3,as4,s4,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2021-03-30 00:00:00,2014,G,69 min,documentary,"pink breaks the mold once again, bringing her ...",amazon,69,min,3.547085
4,as5,s5,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021-03-30 00:00:00,1989,G,45 min,"drama, fantasy",teenage matt banting wants to work with a famo...,amazon,45,min,3.532158

Exporto los archivos csv

In [15]:

plataformas.to_csv('ML_ETL_plataformas.csv',index=False)

In [6]:
ratings.to_csv('ML_ETL_ratins.csv',index=False)